version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
      - npm ci
  
  pre_build:
    commands:
      - echo Running tests...
      - echo No tests configured, proceeding to build phase
  
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Packaging files for deployment...
      # Create deployment bundle
      - mkdir -p deploy
      - cp -r dist deploy/
      - cp -r node_modules deploy/
      - cp -r package.json package-lock.json deploy/
      - cp -r .ebextensions deploy/
      - cp -r Dockerfile deploy/
      - cp -r server deploy/

artifacts:
  files:
    - deploy/**/*
    - package.json
    - package-lock.json
    - .ebextensions/**/*
    - Dockerfile
    - appspec.yml
  discard-paths: no

cache:
  paths:
    - 'node_modules/**/*'